global:
  scrape_interval: 15s
  evaluation_interval: 15s
  scrape_timeout: 10s

scrape_configs:
  - job_name: 'reddit_analysis'
    static_configs:
      - targets: ['api:${API_PORT}']
    metrics_path: '/metrics'
    scheme: http
    scrape_interval: 5s
    scrape_timeout: 4s
    metrics_path: '/metrics'