global:
  scrape_interval: 15s
  evaluation_interval: 15s

# scrape_configs:
#   - job_name: 'reddit-api'
#     static_configs:
#       # - targets: ['api:${API_PORT}']
#       # - targets: ['host.docker.internal:${API_PORT}']
#       - targets: ['127.0.0.1:8017']
#     metrics_path: '/metrics'

scrape_configs:
  - job_name: 'reddit_analysis'
    static_configs:
      - targets: ['api:${API_PORT}']